/*
 * Megacode Kelly monitor tick.
 * B117: ECG / pleth / capno source buffers are generated by the same ACM LifePak functions as the real AED.
 * The panel owns only its local sweep and an AED-compatible beat clock; morphology is not duplicated here.
 */
private _display = uiNamespace getVariable ["ACME_Megacode_DLG",displayNull];
private _dummy = uiNamespace getVariable ["ACME_MC_target",objNull];
if (isNull _display || {isNull _dummy}) exitWith {};

// Keep the LifePak generator pointed at Kelly only while this exclusive dialog is open.
missionNamespace setVariable ["ACM_circulation_AED_Monitor_Target",_dummy];

private _nowDiag = diag_tickTime;
private _lastT = uiNamespace getVariable ["ACME_MC_lastT",_nowDiag];
private _dt = ((_nowDiag-_lastT) max 0) min 0.20;
uiNamespace setVariable ["ACME_MC_lastT",_nowDiag];

// The actual AED electrical-rate writer has its own one-second mutation cadence, so calling it here is safe and
// guarantees PEA/VF/PVT do not inherit Kelly's former fake 20-BPM floor.
private _ekgHR = [_dummy] call ACM_circulation_fnc_updateEKGHeartRate;
private _nativeRhythm = _dummy getVariable ["ACM_circulation_Cardiac_RhythmState",0];
private _effectiveRhythm = [_dummy] call ACME_fnc_rhythmGet;
private _arrest = _dummy getVariable ["ace_medical_inCardiacArrest",false];
private _cpr = alive (_dummy getVariable ["ace_medical_CPR_provider",objNull]);

// AED beat-clock contract, copied semantically from handleAED but without audible beeps. One selected R-R interval
// owns both the next beat epoch and the ECG generator. AFib therefore remains irregular without waveform drift.
if (_ekgHR > 0 && {!(_nativeRhythm in [1,2])}) then {
    private _nominalRR = 60 / (_ekgHR max 1);
    private _clockRhythm = _dummy getVariable ["ACME_AED_ClockRhythm",-999];
    private _lastBeat = _dummy getVariable ["ACM_circulation_AED_Pads_LastBeep",-1];
    private _nextRR = _dummy getVariable ["ACME_AED_NextRR",_nominalRR];
    if (_clockRhythm != _effectiveRhythm) then {
        _dummy setVariable ["ACME_AED_ClockRhythm",_effectiveRhythm,false];
        _nextRR = _nominalRR;
        _dummy setVariable ["ACME_AED_NextRR",_nextRR,false];
        if (_lastBeat < 0 || {(CBA_missionTime-_lastBeat) > ((_nominalRR max 0.25)*1.5)}) then {
            _lastBeat = CBA_missionTime;
            _dummy setVariable ["ACM_circulation_AED_Pads_LastBeep",_lastBeat,false];
            _dummy setVariable ["ACME_AED_PreviousRR",_nextRR,false];
        };
    };
    if (!(_nextRR isEqualType 0) || {!finite _nextRR} || {_nextRR <= 0}) then {_nextRR=_nominalRR;};
    if ((_lastBeat+_nextRR) <= CBA_missionTime) then {
        private _due = _lastBeat+_nextRR;
        private _late = (CBA_missionTime-_due) max 0;
        private _beatAt = if (_late <= ((_nextRR*0.35) min 0.20)) then {_due} else {CBA_missionTime};
        _dummy setVariable ["ACM_circulation_AED_Pads_LastBeep",_beatAt,false];
        _dummy setVariable ["ACME_AED_PreviousRR",_nextRR,false];
        private _newRR = _nominalRR;
        if (_effectiveRhythm in [100,103]) then {
            private _factor = random [0.62,0.94,1.42];
            if (random 1 < 0.20) then {_factor=_factor+random [0.20,0.38,0.72];};
            _newRR = (_nominalRR*_factor) max 0.24;
        };
        _dummy setVariable ["ACME_AED_NextRR",_newRR,false];
        _dummy setVariable ["ACME_AED_LastRR",_nextRR,false];
        _dummy setVariable ["ACME_AED_BeatSerial",(_dummy getVariable ["ACME_AED_BeatSerial",0])+1,false];
    };
};

private _panelHR = _dummy getVariable ["ACME_MC_HR",78];
private _spo2 = (_dummy getVariable ["ACME_MC_SpO2",98]) max 0 min 100;
private _sbp = (_dummy getVariable ["ACME_MC_SBP",122]) max 0;
private _dbp = (_dummy getVariable ["ACME_MC_DBP",78]) max 0;
private _rr = (_dummy getVariable ["ACME_MC_RR",14]) max 0;
private _etco2 = (_dummy getVariable ["ACME_MC_EtCO2",38]) max 0;
private _temp = _dummy getVariable ["ACME_MC_Temp",37];
private _perfusing = [_dummy] call ACM_circulation_fnc_hasPulse;
if (_arrest && {_nativeRhythm == 5}) then {_sbp=0; _dbp=0;};

// The panel HR is the electrical HR, exactly like the LifePak numeric field. PEA therefore has an organized rate
// even with NIBP and pleth at zero. SpO2/pleth require mechanical perfusion.
private _displayHR = round (_ekgHR max 0);
private _displaySpO2 = if (_perfusing || {_cpr}) then {round _spo2} else {0};
private _displayBP = if (_perfusing && {!_arrest}) then {format ["%1/%2",round _sbp,round _dbp]} else {"--/--"};
private _displayEtCO2 = round _etco2;
private _v = uiNamespace getVariable ["ACME_MC_vitalCtrls",createHashMap];
private _setStructured = {
    params ["_map","_key","_text"];
    private _entry = _map getOrDefault [_key,[]];
    if (count _entry < 2) exitWith {};
    _entry params ["_ctrl","_col"];
    if (!isNull _ctrl) then {
        private _hex = switch _key do {case "HR":{"#00ff00"}; case "SpO2":{"#0099ff"}; case "EtCO2":{"#ff8033"}; case "Temp":{"#ffb34d"}; default {"#ffffff"};};
        _ctrl ctrlSetStructuredText parseText format ["<t align='left' size='1.0' color='%1'>%2</t>",_hex,_text];
    };
};
[_v,"HR",str _displayHR] call _setStructured;
[_v,"SpO2",str _displaySpO2] call _setStructured;
[_v,"BP",_displayBP] call _setStructured;
[_v,"EtCO2",str _displayEtCO2] call _setStructured;
[_v,"RR",str (round _rr)] call _setStructured;
[_v,"Temp",format ["%1",(round (_temp*10))/10]] call _setStructured;

// Two consecutive LifePak windows share one boundary sample: 351 points / 350 drawable segments.
// Sampling remains 0.03 s, so morphology is narrower rather than stretching a 176-point sweep across the full panel.
private _stepAcc = (uiNamespace getVariable ["ACME_MC_stepAcc",0]) + _dt;
private _step = uiNamespace getVariable ["ACME_MC_step",1];
private _sampleCount = uiNamespace getVariable ["ACME_MC_sampleCount",351];
if (!(_sampleCount isEqualType 0) || {_sampleCount < 351}) then {_sampleCount = 351;};
private _segmentCount = _sampleCount - 1;
private _sampleSec = 0.03;
private _advance = floor (_stepAcc/_sampleSec);
if (_advance <= 0) exitWith {};
_advance = _advance min 8; // hitch guard: catch up without freezing the UI.
_stepAcc = _stepAcc - (_advance*_sampleSec);
uiNamespace setVariable ["ACME_MC_stepAcc",_stepAcc];

private _trace = uiNamespace getVariable ["ACME_MC_traceCtrls",[]];
private _centers = uiNamespace getVariable ["ACME_MC_laneCenters",[]];
private _waveX = uiNamespace getVariable ["ACME_MC_waveX",0];
private _sampleW = uiNamespace getVariable ["ACME_MC_waveSampleW",0.002];
private _laneH = uiNamespace getVariable ["ACME_MC_laneH",0.08];
if (count _trace < 4 || {count _centers < 4}) exitWith {};

private _sig = format ["%1|%2|%3|%4|%5|%6|%7",_effectiveRhythm,round _ekgHR,round _spo2,round _rr,round _etco2,round _sbp,round _dbp];
private _oldSig = uiNamespace getVariable ["ACME_MC_waveSig",""];
private _buffers = uiNamespace getVariable ["ACME_MC_waveBuffers",[[],[],[],[]]];

private _regenerate = {
    params ["_dummy","_nativeRhythm","_effectiveRhythm","_ekgHR","_spo2","_rr","_etco2","_sbp","_dbp","_perfusing","_cpr"];
    private _spacing = if (_ekgHR > 0) then {(60/_ekgHR)*15} else {0};
    private _rhythmArg = if (_cpr) then {-1} else {_nativeRhythm};
    _dummy setVariable ["ACME_AED_MonitorCursorTime",CBA_missionTime,false];
    _dummy setVariable ["ACM_circulation_AED_UpdateStep",uiNamespace getVariable ["ACME_MC_step",1],false];

    private _buildTwo = {
        params ["_kind","_rhythm","_spacing","_spo2","_etco2","_rr"];
        private _a = []; private _b = [];
        switch _kind do {
            case "ekg": {
                _a = (([_rhythm,_spacing,0] call ACM_circulation_fnc_displayAEDMonitor_generateEKG) param [0,[]]);
                _b = (([_rhythm,_spacing,0] call ACM_circulation_fnc_displayAEDMonitor_generateEKG) param [0,[]]);
            };
            case "po": {
                _a = (([_rhythm,_spacing,0,_spo2] call ACM_circulation_fnc_displayAEDMonitor_generatePO) param [0,[]]);
                _b = (([_rhythm,_spacing,0,_spo2] call ACM_circulation_fnc_displayAEDMonitor_generatePO) param [0,[]]);
            };
            default {
                _a = (([_rhythm,_spacing,0,_etco2,_rr] call ACM_circulation_fnc_displayAEDMonitor_generateCO) param [0,[]]);
                _b = (([_rhythm,_spacing,0,_etco2,_rr] call ACM_circulation_fnc_displayAEDMonitor_generateCO) param [0,[]]);
            };
        };
        // Each native generator returns one complete 176-sample LifePak window. Place two windows back-to-back,
        // sharing a boundary point. Force the second window's first point to the first window's endpoint so random
        // noise cannot create a discontinuity at the join.
        _a resize [176,0];
        _b resize [176,0];
        _b set [0, _a select 175];
        private _out = +_a;
        _b deleteAt 0;
        _out append _b;
        _out resize [351,0];
        _out
    };

    private _ekg = ["ekg",_rhythmArg,_spacing,_spo2,_etco2,_rr] call _buildTwo;
    private _poRhythm = if (_perfusing || {_cpr}) then {_rhythmArg} else {1};
    private _po = ["po",_poRhythm,_spacing,if (_perfusing || {_cpr}) then {_spo2} else {0},_etco2,_rr] call _buildTwo;
    private _coRhythm = if (_rr > 0 && {_etco2 > 0}) then {_rhythmArg} else {1};
    private _co = ["co",_coRhythm,_spacing,_spo2,_etco2,_rr] call _buildTwo;

    // Kelly-only ABP lane. Same 0.03-second timeline, now extended to both displayed windows.
    private _abp = [];
    _abp resize [351,0];
    if (_perfusing && {_ekgHR > 0}) then {
        private _period = 60/(_ekgHR max 1);
        for "_i" from 0 to 350 do {
            private _t = _i*0.03;
            private _ph = (_t mod _period)/_period;
            private _norm = 0;
            if (_ph < 0.12) then {_norm = sin ((_ph/0.12)*90);} else {
                if (_ph < 0.38) then {_norm = 1-((_ph-0.12)/0.26)*0.58;} else {
                    if (_ph < 0.50) then {_norm = 0.42-(sin (((_ph-0.38)/0.12)*180)*0.10);} else {
                        _norm = 0.38*(1-((_ph-0.50)/0.50));
                    };
                };
            };
            _abp set [_i,-((_dbp + ((_sbp-_dbp)*(_norm max 0))) / 2.5)];
        };
    };
    [_ekg,_po,_abp,_co]
};
for "_n" from 1 to _advance do {
    if (_step < 1 || {_step > _segmentCount}) then {_step=1;};
    if (_step == 1 || {_sig != _oldSig} || {(count (_buffers param [0,[]])) < _sampleCount}) then {
        private _sigChanged = _sig != _oldSig;
        if (_sigChanged) then {
            {
                _x params ["_lines","_dots"];
                {_x ctrlShow false;} forEach _lines;
                {_x ctrlShow false;} forEach _dots;
            } forEach _trace;
            _step = 1;
        };
        uiNamespace setVariable ["ACME_MC_step",_step];
        _buffers = [_dummy,_nativeRhythm,_effectiveRhythm,_ekgHR,_spo2,_rr,_etco2,_sbp,_dbp,_perfusing,_cpr] call _regenerate;
        _oldSig = _sig;
        uiNamespace setVariable ["ACME_MC_waveSig",_sig];
        uiNamespace setVariable ["ACME_MC_waveBuffers",_buffers];
    };

    private _prev = _step-1;
    for "_lane" from 0 to 3 do {
        private _buf = _buffers param [_lane,[]];
        if (count _buf < _sampleCount) then {continue};
        private _a = _buf select _prev;
        private _b = _buf select _step;
        private _lanePair = _trace select _lane;
        _lanePair params ["_lines","_dots"];
        if (_prev >= count _lines) then {continue};
        private _line = _lines select _prev;
        private _dot = _dots select _prev;
        private _cy = _centers select _lane;
        private _scale = switch _lane do {case 0:{_laneH/125}; case 1:{_laneH/115}; case 2:{_laneH/105}; default {_laneH/300};};
        private _ya = _cy + (_a*_scale);
        private _yb = _cy + (_b*_scale);
        private _h = _yb-_ya;
        _line ctrlSetPosition [_waveX+(_prev*_sampleW),_ya,_sampleW,_h];
        _line ctrlCommit 0;
        _line ctrlShow true;
        if (abs (_a-_b) < 0.9) then {
            private _dp = ctrlPosition _dot;
            private _d = (_dp select 2) max 0.0012;
            _dot ctrlSetPosition [_waveX+(_prev*_sampleW),_ya-(_d/2),_d,_d];
            _dot ctrlCommit 0;
            _dot ctrlShow true;
        } else {_dot ctrlShow false;};

        // Same forward erase gap as the LifePak sweep: hide a few samples ahead so old and new epochs do not join.
        private _erase = (_prev+6) mod _segmentCount;
        if (_erase < count _lines) then {(_lines select _erase) ctrlShow false; (_dots select _erase) ctrlShow false;};
    };

    _step = _step+1;
    if (_step > _segmentCount) then {_step=1;};
    _dummy setVariable ["ACM_circulation_AED_UpdateStep",_step,false];
};
uiNamespace setVariable ["ACME_MC_step",_step];
